### ISSUE TITLE
Missed letter?

### ISSUE THREAD

**Issue by IanaKhitsko** [ElKoriano/ProgramSystems_CodeReview#1]
https://github.com/ElKoriano/ProgramSystems_CodeReview/blob/7a68574ff9743a17461e7e0f5cc9424a8d193fe6/Okhrymchuk/Python/interface.py#L24

you- > your ?

**Comment by ElKoriano** [comment]
Yes
Sorry
I need to update it soon:)
Я кое-что менял когда Вам сдавал в классе и мне там поменять нужно, забыл
об этом
Лучше меня в последнюю очередь проверять:)

**Comment by OkhrymchukDD** [comment]
Fixed
