### ISSUE TITLE
Possible undefined behaviour

### ISSUE THREAD

**Issue by AlexPenia** [ElKoriano/ProgramSystems_CodeReview#5]
If parsing error does happen, code execution continues anyway using undefined value resulting in potential error or undefined behaviour

https://github.com/ElKoriano/ProgramSystems_CodeReview/blob/051ca892537db9501416280124aebe837078d7e7/Okhrymchuk/Python/interface.py#L13-L17

**Comment by OkhrymchukDD** [comment]
fixed
