### ISSUE TITLE
Wording corrections

### ISSUE THREAD

**Issue by AlexPenia** [ElKoriano/ProgramSystems_CodeReview#7]
Error messages are unclear, like this
https://github.com/ElKoriano/ProgramSystems_CodeReview/blob/051ca892537db9501416280124aebe837078d7e7/Okhrymchuk/Python/interface.py#L25
or have wierd wording (probably "wrong country input format")
https://github.com/ElKoriano/ProgramSystems_CodeReview/blob/051ca892537db9501416280124aebe837078d7e7/Okhrymchuk/Python/interface.py#L34
"Rules" are never mentioned anywhere. What are right and what are wrong rules?
https://github.com/ElKoriano/ProgramSystems_CodeReview/blob/051ca892537db9501416280124aebe837078d7e7/Okhrymchuk/Python/interface.py#L36

**Comment by OkhrymchukDD** [comment]
fixed
